#!/usr/bin/env bash

if [ $(hostname) = "lxl-cjzqn13" ]
then
	network_name="aws-UDP4-443-config"
else
	network_name="aws-UDP4-443-config-linux"
fi

result=$(nmcli -f GENERAL.STATE c show $network_name | grep "activated")


if [ "$1" = "u" ] || [ "$1" = "up" ] || [ "$1" = "on" ]
	then
		nmcli connection up $network_name --ask
	else
		if [ "$1" = "d" ] || [ "$1" = "dn" ] || [ "$1" = "down" ] || [ "$1" = "off" ]
			then
				nmcli connection down $network_name --ask
			else
				if [ -n "$result" ]
					then
						nmcli connection down $network_name --ask
					else
						nmcli connection up $network_name --ask
				fi
		fi
fi

